image: maven:3.9.6-eclipse-temurin-17

stages:
  - build
  - deploy    

build:
  stage: build
  script:
    - mvn clean compile
    
package:
  stage: deploy
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
